services:
  symfony.application:
    class: Symfony\Component\Console\Application
    calls:
      - [add, ['@asfc.PingCommand']]
      - [add, ['@asfc.ListBackupsCommand']]
      - [add, ['@asfc.ListSitesCommand']]
      - [add, ['@asfc.CreateBackupCommand']]
      - [add, ['@asfc.ClearCacheCommand']]
      - [add, ['@asfc.DeleteBackupCommand']]
      - [add, ['@asfc.GetLatestBackupURLCommand']]
      - [add, ['@asfc.GetSiteDetailsCommand']]
      - [add, ['@asfc.SendNotificationCommand']]
      - [add, ['@asfc.ProcessModificationCommand']]

  asfc.ClearCacheCommand:
    class: AppBundle\Commands\ClearCacheCommand
    arguments: ['@asfc.connectorSites']

  asfc.PingCommand:
    class: AppBundle\Commands\PingCommand
    arguments: ['@asfc.connector']

  asfc.ListBackupsCommand:
    class: AppBundle\Commands\ListBackupsCommand
    arguments: ['@asfc.connectorSites']

  asfc.ListSitesCommand:
    class: AppBundle\Commands\ListSitesCommand
    arguments: ['@asfc.connectorSites']

  asfc.CreateBackupCommand:
    class: AppBundle\Commands\CreateBackupCommand
    arguments: ['@asfc.connectorSites']

  asfc.DeleteBackupCommand:
    class: AppBundle\Commands\DeleteBackupCommand
    arguments: ['@asfc.connectorSites']

  asfc.GetLatestBackupURLCommand:
    class: AppBundle\Commands\GetLatestBackupURLCommand
    arguments: ['@asfc.connectorSites']

  asfc.GetSiteDetailsCommand:
    class: AppBundle\Commands\GetSiteDetailsCommand
    arguments: ['@asfc.connectorSites']

  asfc.SendNotificationCommand:
    class: AppBundle\Commands\SendNotificationCommand
    arguments: ['@asfc.connectorThemes']

  asfc.ProcessModificationCommand:
    class: AppBundle\Commands\ProcessModificationCommand
    arguments: ['@asfc.connectorThemes']

  asfc.connector:
    class: AppBundle\Connector\Connector
    arguments: ['@guzzle']

  asfc.connectorSites:
    class: AppBundle\Connector\ConnectorSites
    arguments: ['@asfc.connector']

  symfony.console_output:
    class: Symfony\Component\Console\Output\ConsoleOutput
    public: true

  guzzle:
    class: \GuzzleHttp\Client